# Generated by Django 5.2.5 on 2025-08-06 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المادة')),
                ('description', models.TextField(verbose_name='وصف المادة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='صورة المادة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المنشور')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='مقتطف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='صورة المنشور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المؤلف')),
            ],
            options={
                'verbose_name': 'منشور',
                'verbose_name_plural': 'المنشورات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الملف')),
                ('file_upload', models.FileField(upload_to='study_files/', verbose_name='الملف المرفق')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word Document'), ('ppt', 'PowerPoint'), ('xls', 'Excel'), ('other', 'أخرى')], default='pdf', max_length=10, verbose_name='نوع الملف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='عدد التحميلات')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم الملف (بايت)')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المؤلف')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.course', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'ملف دراسي',
                'verbose_name_plural': 'الملفات الدراسية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='نبذة شخصية')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='الصورة الشخصية')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الشخصي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف شخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الفيديو')),
                ('video_url', models.URLField(verbose_name='رابط الفيديو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='صورة مصغرة')),
                ('duration', models.CharField(blank=True, max_length=20, null=True, verbose_name='مدة الفيديو')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المؤلف')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.course', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'فيديو',
                'verbose_name_plural': 'الفيديوهات',
                'ordering': ['-created_at'],
            },
        ),
    ]
